core.entity_form_display.*.*.*:
  type: config_entity
  label: 'Inline Entity Form display'
  mapping:
    content:
      type: sequence
      label: 'Form display content'
      mapping:
        settings:
          type: sequence
          label: 'Form display settings'
          mapping:
            allow_existing:
              type: boolean
              label: "ALlow existing"
            match_operator:
              type: string
              label: "Match operator"
            delete_references:
              type: boolean
              label: "Delete references"
            override_labels:
              type: boolean
              label: "Override labels"
            label_singular:
              type: string
              label: "Label (singular)"
            label_plural:
              type: string
              label: "Label (plural)"